M48
; DRILL file {KiCad 7.0.7} date Tue Nov  7 23:07:15 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-07T23:07:15-03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0906
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.705Y-4.7467
X5.2223Y-4.7467
T2
X4.398Y-4.755
X5.833Y-2.311
X8.0Y-2.324
X8.004Y-4.766
T0
M30
